# Generated by Django 5.2.7 on 2025-10-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('eid', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('is_onboard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TripTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_time', models.DateTimeField(blank=True, null=True)),
                ('boarding_location', models.CharField(blank=True, max_length=120, null=True)),
                ('alight_time', models.DateTimeField(blank=True, null=True)),
                ('alight_location', models.CharField(blank=True, max_length=120, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
    ]
